### ISSUE TITLE
Release 0.0.4

### ISSUE THREAD

**Issue by joshblum** [uber/multidimensional_urlencode#8]
Support for python3!

**Comment by charlax** [comment]
This will be done this week.

**Comment by joshblum** [comment]
Thanks!!

**Comment by joshblum** [comment]
@charlax just wanted to bump on this, if you could release the new version on pypi.

**Comment by charlax** [comment]
Sorry about that, had actually released this on Friday as promised, but forgot to update this thread.

```
% pip3 install multidimensional_urlencode
[...]
Installing collected packages: multidimensional-urlencode
Successfully installed multidimensional-urlencode-0.0.4
```

**Comment by joshblum** [comment]
thanks!!
